version: '2'
services:
  web:
    image: petrbarborka/odoo_10_dev:latest
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-10-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./sources/addons:/mnt/extra-addons
      - ./sources:/opt/odoo/sources
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-10-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-10-web-data:
  odoo-10-db-data:
